package view;


import controller.ControllerUI;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.DadosInterface;
import model.ValidarQuest;

/**
 *
 * @author joaop
 */
public class AgenteUI extends javax.swing.JFrame {
    private final ControllerUI controlador;
    /**
     * Creates new form Interface
     * @param controlador
     */
    public AgenteUI(ControllerUI controlador) {
        
        try {
            // Define o Look and Feel padrão do sistema
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            System.out.println("Erro ao definir o Look and Feel do sistema: " + e.getMessage());
        }
        
        initComponents();
        this.controlador = controlador;
        painelManual.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpResposta1 = new javax.swing.ButtonGroup();
        grpResposta2 = new javax.swing.ButtonGroup();
        grpResposta3 = new javax.swing.ButtonGroup();
        grpResposta4 = new javax.swing.ButtonGroup();
        grpResposta5 = new javax.swing.ButtonGroup();
        grpResposta6 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        txtTitulo13 = new javax.swing.JLabel();
        painelManual = new javax.swing.JPanel();
        txtTitulo2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        spnPeso = new javax.swing.JSpinner();
        spnPressaoSistolica = new javax.swing.JSpinner();
        spnAtividade = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        txtPeso = new javax.swing.JLabel();
        txtSintoma = new javax.swing.JLabel();
        txtsintomas6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtsintomas3 = new javax.swing.JLabel();
        txtsintomas5 = new javax.swing.JLabel();
        txtsintomas4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtAltura = new javax.swing.JTextField();
        spnPressaoDiastolica = new javax.swing.JSpinner();
        txtAvaliacaoMedica = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        painelManual1 = new javax.swing.JPanel();
        txtPeso1 = new javax.swing.JLabel();
        txtSintoma1 = new javax.swing.JLabel();
        txtsintomas7 = new javax.swing.JLabel();
        txtsintomas8 = new javax.swing.JLabel();
        txtsintomas9 = new javax.swing.JLabel();
        txtsintomas10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        txtTitulo3 = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        btEnviarDiagnostico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel.setLayout(new java.awt.BorderLayout());

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane.setViewportView(txtDiagnostico);

        jPanel.add(jScrollPane, java.awt.BorderLayout.CENTER);

        txtTitulo13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo13.setText("Diagnóstico");
        jPanel.add(txtTitulo13, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 537, 500, 160));

        painelManual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo2.setText("Questionário Médico");
        painelManual.add(txtTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 460, -1));

        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 50, 20));

        spnPeso.setModel(new javax.swing.SpinnerNumberModel(50, 20, 300, 1));
        jPanel2.add(spnPeso);

        spnPressaoSistolica.setModel(new javax.swing.SpinnerNumberModel(120, 20, 300, 10));
        jPanel2.add(spnPressaoSistolica);

        spnAtividade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        jPanel2.add(spnAtividade);

        painelManual.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, 100));

        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 0, 20));

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso.setText("[1] – Insira o Peso:");
        jPanel3.add(txtPeso);

        txtSintoma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSintoma.setText("[3] – Pressão Sistólica:");
        jPanel3.add(txtSintoma);

        txtsintomas6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas6.setText("[5] – Atividades Física:");
        jPanel3.add(txtsintomas6);

        painelManual.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 100));

        jPanel4.setLayout(new java.awt.GridLayout(3, 0, 0, 20));

        txtsintomas3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas3.setText("[2] – Altura do Paciente:");
        jPanel4.add(txtsintomas3);

        txtsintomas5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas5.setText("[4] – Pressão Disatólica:");
        jPanel4.add(txtsintomas5);

        txtsintomas4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas4.setText("[6] – Avaliação Médico");
        jPanel4.add(txtsintomas4);

        painelManual.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 160, 100));

        jPanel5.setLayout(new java.awt.GridLayout(3, 0, 0, 20));
        jPanel5.add(txtAltura);

        spnPressaoDiastolica.setModel(new javax.swing.SpinnerNumberModel(80, 20, 200, 10));
        jPanel5.add(spnPressaoDiastolica);
        jPanel5.add(txtAvaliacaoMedica);

        painelManual.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 60, 100));

        jPanel1.add(painelManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 6, 490, 160));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtPeso1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso1.setText("[1] – Quanto tempo após acordar você fuma seu primeiro cigarro? ");

        txtSintoma1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSintoma1.setText("[2] – Você acha difícil não fumar em lugares proibidos? ");

        txtsintomas7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas7.setText("[3] – Qual cigarro do dia lhe dá mais satisfação? ");

        txtsintomas8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas8.setText("[4] – Quantos cigarros fuma por dia? ");

        txtsintomas9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas9.setText("[5] – Você fuma mais frequentemente pela manhã? ");

        txtsintomas10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas10.setText("[6] – Você fuma mesmo doente, quando precisa ficar de cama?");

        grpResposta1.add(jRadioButton1);
        jRadioButton1.setText("Entre 6 e 30 minutos");

        grpResposta1.add(jRadioButton2);
        jRadioButton2.setText("5 minutos");

        grpResposta1.add(jRadioButton5);
        jRadioButton5.setText("Entre 31 e 60 minutos");

        grpResposta1.add(jRadioButton6);
        jRadioButton6.setText("Após 60 minutos");

        grpResposta2.add(jRadioButton3);
        jRadioButton3.setText("Sim");

        grpResposta2.add(jRadioButton4);
        jRadioButton4.setText("Não");

        grpResposta3.add(jRadioButton9);
        jRadioButton9.setText("Outros");

        grpResposta3.add(jRadioButton10);
        jRadioButton10.setText("O primeiro da manhã");

        grpResposta4.add(jRadioButton11);
        jRadioButton11.setText("Menos de 10");

        grpResposta4.add(jRadioButton12);
        jRadioButton12.setText("De 11 a 20");

        grpResposta4.add(jRadioButton15);
        jRadioButton15.setText("De 21 a 30");

        grpResposta4.add(jRadioButton16);
        jRadioButton16.setText("Mais de 31");

        grpResposta5.add(jRadioButton17);
        jRadioButton17.setText("Sim");

        grpResposta5.add(jRadioButton18);
        jRadioButton18.setText("Não");

        grpResposta6.add(jRadioButton19);
        jRadioButton19.setText("Sim");

        grpResposta6.add(jRadioButton20);
        jRadioButton20.setText("Não");

        txtTitulo3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo3.setText("Questionário Tabagismo");

        javax.swing.GroupLayout painelManual1Layout = new javax.swing.GroupLayout(painelManual1);
        painelManual1.setLayout(painelManual1Layout);
        painelManual1Layout.setHorizontalGroup(
            painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(painelManual1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSintoma1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtsintomas7, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtsintomas8, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jRadioButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jRadioButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jRadioButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtsintomas9, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtsintomas10, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        painelManual1Layout.setVerticalGroup(
            painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManual1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPeso1)
                .addGap(10, 10, 10)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6))))
                .addGap(18, 18, 18)
                .addComponent(txtSintoma1)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addComponent(txtsintomas7)
                .addGap(10, 10, 10)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton9))
                .addGap(18, 18, 18)
                .addComponent(txtsintomas8)
                .addGap(10, 10, 10)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16))
                .addGap(18, 18, 18)
                .addComponent(txtsintomas9)
                .addGap(10, 10, 10)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18))
                .addGap(18, 18, 18)
                .addComponent(txtsintomas10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(painelManual1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 490, 310));

        btLimpar.setBackground(new java.awt.Color(255, 0, 0));
        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 161, -1));

        btEnviarDiagnostico.setBackground(new java.awt.Color(102, 255, 0));
        btEnviarDiagnostico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEnviarDiagnostico.setText("Enviar");
        btEnviarDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarDiagnosticoActionPerformed(evt);
            }
        });
        jPanel1.add(btEnviarDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 161, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        ButtonGroup[] grpBotoes = {grpResposta1, grpResposta2, grpResposta3, grpResposta4, grpResposta5, grpResposta6};      
        for (ButtonGroup grupo : grpBotoes) {
            grupo.clearSelection();
        }
        JSpinner[] grupoSpinner = {spnPressaoSistolica, spnPressaoDiastolica, spnAtividade, spnPeso};    
        for (JSpinner spinner : grupoSpinner) {
            spinner.setValue(null);
        }
    }//GEN-LAST:event_btLimparActionPerformed

    
    private boolean verificarValoresNulos(ButtonGroup[] grpBotoes, JSpinner[] grupoSpinner, JTextField[] grupoValores) {
        
        for (ButtonGroup grupo : grpBotoes) {
            if (grupo.getSelection() == null) {
                return true; // Encontrou um botão não selecionado
            }
        }
        for (JSpinner spinner : grupoSpinner) {
            if (spinner.getValue() == null) {
                return true; // Encontrou um spinner com valor nulo
            }
        }
        
        for (JTextField valor : grupoValores) {
            if (valor.getText()== null || valor.getText().isEmpty()) {
                return true; // Encontrou um campo de texto formatado com valor nulo ou vazio
            }
        }
        
        try {
            Double.valueOf(txtAltura.getText());
            Integer.valueOf(spnPeso.getValue().toString());
            Integer.valueOf(spnPressaoSistolica.getValue().toString());
            Integer.valueOf(spnPressaoDiastolica.getValue().toString());
            Integer.valueOf(spnAtividade.getValue().toString());
            ValidarQuest.calcularPontuacaoTotal(grpBotoes);
            Double.valueOf(txtAvaliacaoMedica.getText());
            
            
        } catch (NumberFormatException e) {
            return true;
        }
        
        return false; // Nenhum valor nulo encontrado
    }
    
    
      
    
    private void btEnviarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarDiagnosticoActionPerformed
       ButtonGroup[] grpBotoes = {grpResposta1, grpResposta2, grpResposta3, grpResposta4, grpResposta5, grpResposta6};  
       JSpinner[] grupoSpinner = {spnPressaoSistolica, spnPressaoDiastolica, spnAtividade, spnPeso};    
       JTextField[] grupoValores = {txtAvaliacaoMedica,txtAltura};

       
        if(verificarValoresNulos(grpBotoes, grupoSpinner, grupoValores)){
            txtDiagnostico.setText(" Preencha todos os campos!!!");
        }else{
            
            double[] dados = {
                Double.parseDouble(txtAltura.getText()),
                Double.parseDouble(spnPeso.getValue().toString()),
                Double.parseDouble(spnPressaoSistolica.getValue().toString()),
                Double.parseDouble(spnPressaoDiastolica.getValue().toString()),
                Double.parseDouble(spnAtividade.getValue().toString()),
                ValidarQuest.calcularPontuacaoTotal(grpBotoes),
                Double.parseDouble(txtAvaliacaoMedica.getText())
            };

            DadosInterface dadosInterface = new DadosInterface(
                dados[0], dados[1], dados[2], dados[3], dados[4], dados[5], dados[6]
            );
            String resposta = controlador.enviarDiagnostico(dadosInterface);
            txtDiagnostico.setText(resposta);
        }
    }//GEN-LAST:event_btEnviarDiagnosticoActionPerformed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviarDiagnostico;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup grpResposta1;
    private javax.swing.ButtonGroup grpResposta2;
    private javax.swing.ButtonGroup grpResposta3;
    private javax.swing.ButtonGroup grpResposta4;
    private javax.swing.ButtonGroup grpResposta5;
    private javax.swing.ButtonGroup grpResposta6;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel painelManual;
    private javax.swing.JPanel painelManual1;
    private javax.swing.JSpinner spnAtividade;
    private javax.swing.JSpinner spnPeso;
    private javax.swing.JSpinner spnPressaoDiastolica;
    private javax.swing.JSpinner spnPressaoSistolica;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAvaliacaoMedica;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtPeso1;
    private javax.swing.JLabel txtSintoma;
    private javax.swing.JLabel txtSintoma1;
    private javax.swing.JLabel txtTitulo13;
    private javax.swing.JLabel txtTitulo2;
    private javax.swing.JLabel txtTitulo3;
    private javax.swing.JLabel txtsintomas10;
    private javax.swing.JLabel txtsintomas3;
    private javax.swing.JLabel txtsintomas4;
    private javax.swing.JLabel txtsintomas5;
    private javax.swing.JLabel txtsintomas6;
    private javax.swing.JLabel txtsintomas7;
    private javax.swing.JLabel txtsintomas8;
    private javax.swing.JLabel txtsintomas9;
    // End of variables declaration//GEN-END:variables

    
}
