package view;

import controller.ControllerUI;
import javax.swing.ButtonGroup;
import javax.swing.JSpinner;
import model.DadosInterface;
import model.ValidarQuest;


/**
 *
 * @author joaop
 */
public class AgenteUI extends javax.swing.JFrame {
    private final ControllerUI controlador;
    /**
     * Creates new form Interface
     * @param controlador
     */
    public AgenteUI(ControllerUI controlador) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        initComponents();
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(12);
        this.controlador = controlador;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpResposta1 = new javax.swing.ButtonGroup();
        grpResposta2 = new javax.swing.ButtonGroup();
        grpResposta3 = new javax.swing.ButtonGroup();
        grpResposta4 = new javax.swing.ButtonGroup();
        grpResposta5 = new javax.swing.ButtonGroup();
        grpResposta6 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        painelManual1 = new javax.swing.JPanel();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        txtPeso1 = new javax.swing.JLabel();
        txtSintoma1 = new javax.swing.JLabel();
        txtsintomas7 = new javax.swing.JLabel();
        txtsintomas8 = new javax.swing.JLabel();
        txtsintomas9 = new javax.swing.JLabel();
        txtsintomas10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtPeso3 = new javax.swing.JLabel();
        txtsintomas11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        spnPeso = new javax.swing.JSpinner();
        txtAltura = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        txtSintoma3 = new javax.swing.JLabel();
        txtsintomas6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        spnPressaoSistolica = new javax.swing.JSpinner();
        spnPressaoDiastolica = new javax.swing.JSpinner();
        jPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        txtTitulo13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTitulo4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtSintoma2 = new javax.swing.JLabel();
        txtsintomas5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        spnAvaliacaoMedica = new javax.swing.JSpinner();
        spnAtvidades = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        btLimpar = new javax.swing.JButton();
        btEnviarDiagnostico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        painelManual1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "QUESTIONÁRIO TABAGISMO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        grpResposta5.add(jRadioButton22);
        jRadioButton22.setText("Não fumo");

        grpResposta1.add(jRadioButton5);
        jRadioButton5.setText("Entre 31 e 60 minutos");

        grpResposta1.add(jRadioButton6);
        jRadioButton6.setText("Após 60 minutos");

        grpResposta2.add(jRadioButton3);
        jRadioButton3.setText("Sim");

        grpResposta2.add(jRadioButton4);
        jRadioButton4.setText("Não");

        grpResposta3.add(jRadioButton9);
        jRadioButton9.setText("Outros");

        grpResposta3.add(jRadioButton10);
        jRadioButton10.setText("O primeiro da manhã");

        grpResposta4.add(jRadioButton11);
        jRadioButton11.setText("Menos de 10");

        grpResposta4.add(jRadioButton12);
        jRadioButton12.setText("De 11 a 20");

        grpResposta4.add(jRadioButton15);
        jRadioButton15.setText("De 21 a 30");

        grpResposta4.add(jRadioButton16);
        jRadioButton16.setText("Mais de 31");

        txtPeso1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtPeso1.setText("[1] – Quanto tempo após acordar você fuma o primeiro cigarro? ");

        txtSintoma1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtSintoma1.setText("[2] – Você acha difícil não fumar em lugares proibidos? ");

        txtsintomas7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtsintomas7.setText("[3] – Qual cigarro do dia lhe dá mais satisfação? ");

        txtsintomas8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtsintomas8.setText("[4] – Quantos cigarros fuma por dia? ");

        txtsintomas9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtsintomas9.setText("[5] – Você fuma mais frequentemente pela manhã? ");

        txtsintomas10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtsintomas10.setText("[6] – Você fuma mesmo doente, quando precisa ficar de cama?");

        grpResposta1.add(jRadioButton1);
        jRadioButton1.setText("Entre 6 e 30 minutos");

        grpResposta1.add(jRadioButton2);
        jRadioButton2.setText("5 minutos");

        grpResposta5.add(jRadioButton17);
        jRadioButton17.setText("Sim");

        grpResposta5.add(jRadioButton18);
        jRadioButton18.setText("Não");

        grpResposta6.add(jRadioButton19);
        jRadioButton19.setText("Sim");

        grpResposta6.add(jRadioButton20);
        jRadioButton20.setText("Não");

        grpResposta4.add(jRadioButton7);
        jRadioButton7.setText("Não fumo");

        grpResposta2.add(jRadioButton8);
        jRadioButton8.setText("Não fumo");

        grpResposta3.add(jRadioButton13);
        jRadioButton13.setText("Não fumo");

        grpResposta1.add(jRadioButton14);
        jRadioButton14.setText("Não fumo");

        grpResposta6.add(jRadioButton21);
        jRadioButton21.setText("Não fumo");

        javax.swing.GroupLayout painelManual1Layout = new javax.swing.GroupLayout(painelManual1);
        painelManual1.setLayout(painelManual1Layout);
        painelManual1Layout.setHorizontalGroup(
            painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManual1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtSintoma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtsintomas7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtsintomas8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(101, 101, 101))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtsintomas9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtsintomas10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(170, 170, 170))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelManual1Layout.setVerticalGroup(
            painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManual1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtPeso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)))
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(txtSintoma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(txtsintomas7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(txtsintomas8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(txtsintomas9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(txtsintomas10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );

        jScrollPane2.setViewportView(painelManual1);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "IMC", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jPanel13.setLayout(new java.awt.GridLayout(2, 0));

        txtPeso3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso3.setText("Insira o Peso:");
        jPanel13.add(txtPeso3);

        txtsintomas11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas11.setText("Insira a Altura:");
        jPanel13.add(txtsintomas11);

        jPanel14.setLayout(new java.awt.GridLayout(2, 1, 50, 10));

        spnPeso.setModel(new javax.swing.SpinnerNumberModel(80, 20, 300, 1));
        jPanel14.add(spnPeso);

        txtAltura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAltura.setText("1.70");
        jPanel14.add(txtAltura);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Pressão Arterial", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jPanel16.setLayout(new java.awt.GridLayout(2, 0));

        txtSintoma3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSintoma3.setText("Pressão Sistólica:");
        jPanel16.add(txtSintoma3);

        txtsintomas6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas6.setText("Pressão Diastólica:");
        jPanel16.add(txtsintomas6);

        jPanel17.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        spnPressaoSistolica.setModel(new javax.swing.SpinnerNumberModel(120, 20, 300, 10));
        jPanel17.add(spnPressaoSistolica);

        spnPressaoDiastolica.setModel(new javax.swing.SpinnerNumberModel(80, 20, 200, 10));
        jPanel17.add(spnPressaoDiastolica);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel.setLayout(new java.awt.BorderLayout());

        txtDiagnostico.setEditable(false);
        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane.setViewportView(txtDiagnostico);

        jPanel.add(jScrollPane, java.awt.BorderLayout.CENTER);

        txtTitulo13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo13.setText("Diagnóstico");
        jPanel.add(txtTitulo13, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        txtTitulo4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo4.setText("AVALIADOR DE RISCO CARDÍACO");
        jPanel3.add(txtTitulo4);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Avaliação", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jPanel11.setLayout(new java.awt.GridLayout(2, 0));

        txtSintoma2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSintoma2.setText("Avaliação Médica");
        jPanel11.add(txtSintoma2);

        txtsintomas5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas5.setText("Atvidades Semanais");
        jPanel11.add(txtsintomas5);

        jPanel12.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        spnAvaliacaoMedica.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 10));
        jPanel12.add(spnAvaliacaoMedica);

        spnAtvidades.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        jPanel12.add(spnAtvidades);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        btLimpar.setBackground(new java.awt.Color(255, 0, 0));
        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLimpar.setText("Limpar questionário");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel6.add(btLimpar);

        btEnviarDiagnostico.setBackground(new java.awt.Color(102, 255, 0));
        btEnviarDiagnostico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEnviarDiagnostico.setText("Enviar");
        btEnviarDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarDiagnosticoActionPerformed(evt);
            }
        });
        jPanel6.add(btEnviarDiagnostico);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparGruposDeBotoes();
    }//GEN-LAST:event_btLimparActionPerformed

    
    private void btEnviarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarDiagnosticoActionPerformed
        if (verificarCamposNulos()) {
            txtDiagnostico.setText("Preencha todos os campos!!!");
        } else {
             double[] dados = obterDados();
            DadosInterface dadosInterface = new DadosInterface(
                dados[0], dados[1], dados[2], dados[3], dados[4], dados[5], dados[6]
            );
            String resposta = controlador.enviarDados(dadosInterface).getMensagem();
            txtDiagnostico.setText(resposta);
        }
    }//GEN-LAST:event_btEnviarDiagnosticoActionPerformed


    private void limparGruposDeBotoes() {
        ButtonGroup[] gruposDeBotoes = {grpResposta1, grpResposta2, grpResposta3, grpResposta4, grpResposta5, grpResposta6};
        for (ButtonGroup grupo : gruposDeBotoes) {
            grupo.clearSelection();
        }
    }

    private boolean verificarCamposNulos() {
        return algumBotaoNaoSelecionado() || algumSpinnerNulo() || camposInvalidos();
    }

    private boolean algumBotaoNaoSelecionado() {
        ButtonGroup[] gruposDeBotoes = {grpResposta1, grpResposta2, grpResposta3, grpResposta4, grpResposta5, grpResposta6};
        for (ButtonGroup grupo : gruposDeBotoes) {
            if (grupo.getSelection() == null) {
                return true;
            }
        }
        return false;
    }

    private boolean algumSpinnerNulo() {
        JSpinner[] grupoSpinner = {spnAvaliacaoMedica, spnAtvidades};
        for (JSpinner spinner : grupoSpinner) {
            if (spinner.getValue() == null) {
                return true;
            }
        }
        return false;
    }

    private boolean camposInvalidos() {
        try {
            Double.valueOf(txtAltura.getText());
            Double.valueOf(spnPeso.getValue().toString());
            Double.valueOf(spnPressaoDiastolica.getValue().toString());
            Double.valueOf(spnPressaoSistolica.getValue().toString());
            Double.valueOf(spnAtvidades.getValue().toString());
            Double.valueOf(spnAvaliacaoMedica.getValue().toString());
            ValidarQuest.calcularPontuacaoTotal(new ButtonGroup[]{grpResposta1, grpResposta2, grpResposta3, grpResposta4, grpResposta5, grpResposta6});
        } catch (NumberFormatException e) {
            return true;
        }
        return false;
    }

    private double[] obterDados() {
        double altura = Double.parseDouble(txtAltura.getText());
        double peso = Double.parseDouble(spnPeso.getValue().toString());
        double pressaoSistolica = Double.parseDouble(spnPressaoSistolica.getValue().toString());
        double pressaoDiastolica = Double.parseDouble(spnPressaoDiastolica.getValue().toString());
        double atividade = Double.parseDouble(spnAtvidades.getValue().toString());
        double pontuacaoTotal = ValidarQuest.calcularPontuacaoTotal(new ButtonGroup[]{grpResposta1, grpResposta2, grpResposta3, grpResposta4, grpResposta5, grpResposta6});
        double avaliacao = Double.parseDouble(spnAvaliacaoMedica.getValue().toString()) / 100;

        return new double[]{altura, peso, pressaoSistolica, pressaoDiastolica, atividade, pontuacaoTotal, avaliacao};
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviarDiagnostico;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup grpResposta1;
    private javax.swing.ButtonGroup grpResposta2;
    private javax.swing.ButtonGroup grpResposta3;
    private javax.swing.ButtonGroup grpResposta4;
    private javax.swing.ButtonGroup grpResposta5;
    private javax.swing.ButtonGroup grpResposta6;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelManual1;
    private javax.swing.JSpinner spnAtvidades;
    private javax.swing.JSpinner spnAvaliacaoMedica;
    private javax.swing.JSpinner spnPeso;
    private javax.swing.JSpinner spnPressaoDiastolica;
    private javax.swing.JSpinner spnPressaoSistolica;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JLabel txtPeso1;
    private javax.swing.JLabel txtPeso3;
    private javax.swing.JLabel txtSintoma1;
    private javax.swing.JLabel txtSintoma2;
    private javax.swing.JLabel txtSintoma3;
    private javax.swing.JLabel txtTitulo13;
    private javax.swing.JLabel txtTitulo4;
    private javax.swing.JLabel txtsintomas10;
    private javax.swing.JLabel txtsintomas11;
    private javax.swing.JLabel txtsintomas5;
    private javax.swing.JLabel txtsintomas6;
    private javax.swing.JLabel txtsintomas7;
    private javax.swing.JLabel txtsintomas8;
    private javax.swing.JLabel txtsintomas9;
    // End of variables declaration//GEN-END:variables

    
}
