package view;


import controller.ControllerInterface;
import javax.swing.ButtonGroup;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.DadosInterface;
import model.ValidarQuestionario;

/**
 *
 * @author joaop
 */
public class Interface extends javax.swing.JFrame {
    private final ControllerInterface controlador;
    /**
     * Creates new form Interface
     * @param controlador
     */
    public Interface(ControllerInterface controlador) {
        
        try {
            // Define o Look and Feel para o tema Nimbus
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            System.out.println("Erro ao definir o tema Nimbus: " + e.getMessage());
        }
        initComponents();
        this.controlador = controlador;
        painelManual.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpResposta1 = new javax.swing.ButtonGroup();
        grpResposta2 = new javax.swing.ButtonGroup();
        grpResposta3 = new javax.swing.ButtonGroup();
        grpResposta4 = new javax.swing.ButtonGroup();
        grpResposta5 = new javax.swing.ButtonGroup();
        grpResposta6 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        txtTitulo13 = new javax.swing.JLabel();
        txtTitulo3 = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        btEnviarDiagnostico = new javax.swing.JButton();
        painelManual1 = new javax.swing.JPanel();
        txtPeso1 = new javax.swing.JLabel();
        txtSintoma1 = new javax.swing.JLabel();
        txtsintomas7 = new javax.swing.JLabel();
        txtsintomas8 = new javax.swing.JLabel();
        txtsintomas9 = new javax.swing.JLabel();
        txtsintomas10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        painelManual = new javax.swing.JPanel();
        txtPeso = new javax.swing.JLabel();
        txtsintomas3 = new javax.swing.JLabel();
        txtSintoma = new javax.swing.JLabel();
        txtsintomas5 = new javax.swing.JLabel();
        txtsintomas6 = new javax.swing.JLabel();
        txtTitulo2 = new javax.swing.JLabel();
        spnPressaoSistolica = new javax.swing.JSpinner();
        spnPeso = new javax.swing.JSpinner();
        spnPressaoDiastolica = new javax.swing.JSpinner();
        spnAtividade = new javax.swing.JSpinner();
        txtsintomas4 = new javax.swing.JLabel();
        txtAvaliacaoMedica = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setLayout(new java.awt.BorderLayout());

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane.setViewportView(txtDiagnostico);

        jPanel.add(jScrollPane, java.awt.BorderLayout.CENTER);

        txtTitulo13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo13.setText("Diagnóstico");
        jPanel.add(txtTitulo13, java.awt.BorderLayout.PAGE_START);

        txtTitulo3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo3.setText("Questionário Tabagismo");

        btLimpar.setBackground(new java.awt.Color(255, 0, 0));
        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btEnviarDiagnostico.setBackground(new java.awt.Color(102, 255, 0));
        btEnviarDiagnostico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEnviarDiagnostico.setText("Enviar");
        btEnviarDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarDiagnosticoActionPerformed(evt);
            }
        });

        txtPeso1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso1.setText("[1] – Quanto tempo após acordar você fuma seu primeiro cigarro? ");

        txtSintoma1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSintoma1.setText("[2] – Você acha difícil não fumar em lugares proibidos? ");

        txtsintomas7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas7.setText("[3] – Qual cigarro do dia lhe dá mais satisfação? ");

        txtsintomas8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas8.setText("[4] – Quantos cigarros fuma por dia? ");

        txtsintomas9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas9.setText("[5] – Você fuma mais frequentemente pela manhã? ");

        txtsintomas10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas10.setText("[6] – Você fuma mesmo doente, quando precisa ficar de cama?");

        grpResposta1.add(jRadioButton1);
        jRadioButton1.setText("Entre 6 e 30 minutos");

        grpResposta1.add(jRadioButton2);
        jRadioButton2.setText("5 minutos");

        grpResposta1.add(jRadioButton5);
        jRadioButton5.setText("Entre 31 e 60 minutos");

        grpResposta1.add(jRadioButton6);
        jRadioButton6.setText("Após 60 minutos");

        grpResposta2.add(jRadioButton3);
        jRadioButton3.setText("Sim");

        grpResposta2.add(jRadioButton4);
        jRadioButton4.setText("Não");

        grpResposta3.add(jRadioButton9);
        jRadioButton9.setText("Outros");

        grpResposta3.add(jRadioButton10);
        jRadioButton10.setText("O primeiro da manhã");

        grpResposta4.add(jRadioButton11);
        jRadioButton11.setText("Menos de 10");

        grpResposta4.add(jRadioButton12);
        jRadioButton12.setText("De 11 a 20");

        grpResposta4.add(jRadioButton15);
        jRadioButton15.setText("De 21 a 30");

        grpResposta4.add(jRadioButton16);
        jRadioButton16.setText("Mais de 31");

        grpResposta5.add(jRadioButton17);
        jRadioButton17.setText("Sim");

        grpResposta5.add(jRadioButton18);
        jRadioButton18.setText("Não");

        grpResposta6.add(jRadioButton19);
        jRadioButton19.setText("Sim");

        grpResposta6.add(jRadioButton20);
        jRadioButton20.setText("Não");

        javax.swing.GroupLayout painelManual1Layout = new javax.swing.GroupLayout(painelManual1);
        painelManual1.setLayout(painelManual1Layout);
        painelManual1Layout.setHorizontalGroup(
            painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManual1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtSintoma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(160, 160, 160))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(401, 401, 401))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtsintomas7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(205, 205, 205))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(294, 294, 294))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtsintomas8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(274, 274, 274))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtsintomas9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(185, 185, 185))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(jRadioButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(377, 377, 377))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtsintomas10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(111, 111, 111))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(jRadioButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(361, 361, 361))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(txtPeso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jRadioButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(110, 110, 110))
                    .addGroup(painelManual1Layout.createSequentialGroup()
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        painelManual1Layout.setVerticalGroup(
            painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManual1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPeso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addComponent(txtSintoma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(txtsintomas7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(txtsintomas8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(txtsintomas9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(txtsintomas10, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(painelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        painelManual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso.setText("[1] – Insira o Peso:");
        painelManual.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, -1, -1));

        txtsintomas3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas3.setText("[2] – Altura do Paciente:");
        painelManual.add(txtsintomas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        txtSintoma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSintoma.setText("[3] – Pressão Sistólica:");
        painelManual.add(txtSintoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, -1, -1));

        txtsintomas5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas5.setText("[4] – Pressão Disatólica:");
        painelManual.add(txtsintomas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 144, -1));

        txtsintomas6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas6.setText("[5] – Atividades Física:");
        painelManual.add(txtsintomas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, -1, -1));

        txtTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo2.setText("Questionário Médico");
        painelManual.add(txtTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 492, -1));

        spnPressaoSistolica.setModel(new javax.swing.SpinnerNumberModel(120, 20, 300, 10));
        painelManual.add(spnPressaoSistolica, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 100, 80, -1));

        spnPeso.setModel(new javax.swing.SpinnerNumberModel(50, 20, 300, 1));
        painelManual.add(spnPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 56, 80, -1));

        spnPressaoDiastolica.setModel(new javax.swing.SpinnerNumberModel(80, 20, 200, 10));
        painelManual.add(spnPressaoDiastolica, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, -1));

        spnAtividade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        painelManual.add(spnAtividade, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 146, 80, -1));

        txtsintomas4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsintomas4.setText("[6] – Avaliação Médico");
        painelManual.add(txtsintomas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 144, -1));
        painelManual.add(txtAvaliacaoMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 50, -1));
        painelManual.add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 50, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelManual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addGap(59, 59, 59)
                    .addComponent(btEnviarDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGap(117, 117, 117)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelManual, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelManual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(729, 729, 729)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btEnviarDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(225, 225, 225)))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        ButtonGroup[] grpBotoes = {grpResposta1, grpResposta2, grpResposta3, grpResposta4, grpResposta5, grpResposta6};      
        for (ButtonGroup grupo : grpBotoes) {
            grupo.clearSelection();
        }
        JSpinner[] grupoSpinner = {spnPressaoSistolica, spnPressaoDiastolica, spnAtividade, spnPeso};    
        for (JSpinner spinner : grupoSpinner) {
            spinner.setValue(null);
        }
    }//GEN-LAST:event_btLimparActionPerformed

    
    private boolean verificarValoresNulos(ButtonGroup[] grpBotoes, JSpinner[] grupoSpinner, JTextField[] grupoValores) {
        
        for (ButtonGroup grupo : grpBotoes) {
            if (grupo.getSelection() == null) {
                return true; // Encontrou um botão não selecionado
            }
        }
        for (JSpinner spinner : grupoSpinner) {
            if (spinner.getValue() == null) {
                return true; // Encontrou um spinner com valor nulo
            }
        }
        
        for (JTextField valor : grupoValores) {
            if (valor.getText()== null || valor.getText().isEmpty()) {
                return true; // Encontrou um campo de texto formatado com valor nulo ou vazio
            }
        }
        
        try {
            Double.valueOf(txtAltura.getText());
            Integer.valueOf(spnPeso.getValue().toString());
            Integer.valueOf(spnPressaoSistolica.getValue().toString());
            Integer.valueOf(spnPressaoDiastolica.getValue().toString());
            Integer.valueOf(spnAtividade.getValue().toString());
            ValidarQuestionario.calcularPontuacaoTotal(grpBotoes);
            Double.valueOf(txtAvaliacaoMedica.getText());
            
            
        } catch (NumberFormatException e) {
            return true;
        }
        
        return false; // Nenhum valor nulo encontrado
    }
    
    
      
    
    private void btEnviarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarDiagnosticoActionPerformed
       ButtonGroup[] grpBotoes = {grpResposta1, grpResposta2, grpResposta3, grpResposta4, grpResposta5, grpResposta6};  
       JSpinner[] grupoSpinner = {spnPressaoSistolica, spnPressaoDiastolica, spnAtividade, spnPeso};    
       JTextField[] grupoValores = {txtAvaliacaoMedica,txtAltura};

       
        if(verificarValoresNulos(grpBotoes, grupoSpinner, grupoValores)){
            txtDiagnostico.setText(" Preencha todos os campos!!!");
        }else{
            
            double[] dados = {
                Double.parseDouble(txtAltura.getText()),
                Double.parseDouble(spnPeso.getValue().toString()),
                Double.parseDouble(spnPressaoSistolica.getValue().toString()),
                Double.parseDouble(spnPressaoDiastolica.getValue().toString()),
                Double.parseDouble(spnAtividade.getValue().toString()),
                ValidarQuestionario.calcularPontuacaoTotal(grpBotoes),
                Double.parseDouble(txtAvaliacaoMedica.getText())
            };

            DadosInterface dadosInterface = new DadosInterface(
                dados[0], dados[1], dados[2], dados[3], dados[4], dados[5], dados[6]
            );
            String resposta = controlador.enviarDiagnostico(dadosInterface);
            txtDiagnostico.setText(resposta);
        }
    }//GEN-LAST:event_btEnviarDiagnosticoActionPerformed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviarDiagnostico;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup grpResposta1;
    private javax.swing.ButtonGroup grpResposta2;
    private javax.swing.ButtonGroup grpResposta3;
    private javax.swing.ButtonGroup grpResposta4;
    private javax.swing.ButtonGroup grpResposta5;
    private javax.swing.ButtonGroup grpResposta6;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelManual;
    private javax.swing.JPanel painelManual1;
    private javax.swing.JSpinner spnAtividade;
    private javax.swing.JSpinner spnPeso;
    private javax.swing.JSpinner spnPressaoDiastolica;
    private javax.swing.JSpinner spnPressaoSistolica;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAvaliacaoMedica;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtPeso1;
    private javax.swing.JLabel txtSintoma;
    private javax.swing.JLabel txtSintoma1;
    private javax.swing.JLabel txtTitulo13;
    private javax.swing.JLabel txtTitulo2;
    private javax.swing.JLabel txtTitulo3;
    private javax.swing.JLabel txtsintomas10;
    private javax.swing.JLabel txtsintomas3;
    private javax.swing.JLabel txtsintomas4;
    private javax.swing.JLabel txtsintomas5;
    private javax.swing.JLabel txtsintomas6;
    private javax.swing.JLabel txtsintomas7;
    private javax.swing.JLabel txtsintomas8;
    private javax.swing.JLabel txtsintomas9;
    // End of variables declaration//GEN-END:variables

    
}
